### ISSUE TITLE
[TSK-281] Modify saving of tweets by making name unique

### ISSUE THREAD

**Issue by iamMihirT** [dream-aim-deliver/mpi-sda-twitter-scraper#7]

**Comment by ghost** [comment]
@iamMihirT , whats the status of this activity?

**Comment by iamMihirT** [comment]
I have completed the coding part and want to test it locally. Once done I will send the PR. Should be done by today.

**Comment by ghost** [comment]
@alebg, could you review it?

**Comment by ghost** [comment]
@ydamit, could you review it?

**Comment by ydamit** [comment]
It looks like there are two different PRs connected to this issue, with potentially conflicting changes to scraper.py:

1.  [[TSK-281] Changes in file saving and Input Parameter](https://github.com/dream-aim-deliver/mpi-sda-twitter-scraper/pull/8)
2. [Filename Changes](https://github.com/dream-aim-deliver/mpi-sda-twitter-scraper/pull/10)

Does one supersede the other? Or should I review them both in a specific sequence?
